#include <iostream>
#include <string.h>
#include "types.h"
#include "utils.h"

using namespace std;

int main() {
    human **people =  new human*[10];
    // only this part of the code is generated by chatGPT
    // cuase I'm too lazy to make 20 random instances of a struct
    // although I changed it to allocate memory dynamically
    // and yes chatGPT wouldn't do it (exactly how I wanted to do) no matter how I told it to do
    people[0] = new human{"John", new char[4]{"Doe"}, 123456, 25};
    people[1] = new human{"Alice", new char[6]{"Smith"}, 234567, 30};
    people[2] = new human{"Robert", new char[6]{"Brown"}, 345678, 40};
    people[3] = new human{"Mary", new char[8]{"Johnson"}, 456789, 35};
    people[4] = new human{"James", new char[6]{"Davis"}, 567890, 45};
    people[5] = new human{"Patricia", new char[7]{"Garcia"}, 612345, 28};
    people[6] = new human{"Michael", new char[7]{"Miller"}, 783456, 50};
    people[7] = new human{"Linda", new char[9]{"Martinez"}, 890123, 22};
    people[8] = new human{"David", new char[9]{"Gonzalez"}, 901234, 33};
    people[9] = new human{"Barbara", new char[7]{"Wilson"}, 127009, 27};

    student **students = new student*[10];
    students[0] = new student{*people[0], 1001, "Computer Science", 3.8};
    students[1] = new student{*people[1], 1002, "Mathematics", 3.6};
    students[2] = new student{*people[2], 1003, "Physics", 3.9};
    students[3] = new student{*people[3], 1004, "Chemistry", 3.5};
    students[4] = new student{*people[4], 1005, "Biology", 3.4};
    students[5] = new student{*people[5], 1006, "Economics", 3.7};
    students[6] = new student{*people[6], 1007, "Engineering", 3.2};
    students[7] = new student{*people[7], 1008, "History", 3.3};
    students[8] = new student{*people[8], 1009, "Philosophy", 3.8};
    students[9] = new student{*people[0], 1010, "Psychology", 3.9};
    // end of chatGPT

    for (int i = 0; i < 3; i++) {
        cout << "name: " << people[i]->name << endl;
        cout << "family: " << people[i]->family << endl;
        cout << "age: " << people[i]->age << endl;
    }
    for (int i = 0; i < 3; i++) {
        cout << "name: " << people[i]->name << endl;
        cout << "family: " << people[i]->family << endl;
        cout << "age: " << people[i]->age << endl;
    }
    
    target_sec(people, 10);
    target_sec(students, 10);
    target_sec(students, 10, false);
    target_sec(students, 10, true);

    killPeople(people, 10);
    killStudents(students, 10);
    return 0;
}